apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flux-model-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-wait
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
