apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cogvideox-serve
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.ingress.staticIpName }}"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /generate
            pathType: Prefix
            backend:
              service:
                name: cogvideox-serve
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: cogvideox-serve
                port:
                  number: 80
