apiVersion: v1
kind: Service
metadata:
  name: cogvideox-serve
  labels:
    app: cogvideox-serve
  annotations:
    cloud.google.com/backend-config: '{"default": "cogvideox-serve-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: cogvideox-serve
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
