apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-serve-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llama-serve-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llama-serve-rolebinding
subjects:
  - kind: ServiceAccount
    name: llama-serve-sa
roleRef:
  kind: Role
  name: llama-serve-role
  apiGroup: rbac.authorization.k8s.io
