name: Build and Push serving Image

on:
  push:
    branches: [main]
    paths:
      - 'transformer/serve/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ghcr.io/ironfistofgod/gpt-serve:latest -t ghcr.io/ironfistofgod/gpt-serve:${{ github.sha }} ./transformer/serve
      - name: Push image
        run: |
          docker push ghcr.io/ironfistofgod/gpt-serve:latest
          docker push ghcr.io/ironfistofgod/gpt-serve:${{ github.sha }}
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ml-portfolio
          location: us-central1-a
      
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/gpt-serve gpt-serve=ghcr.io/ironfistofgod/gpt-serve:${{ github.sha }}
          kubectl rollout status deployment/gpt-serve